### ISSUE TITLE
How to ensure the content of Actions_01-49.txt and Actions_50-60.txt

### ISSUE THREAD

**Issue by JiajiaStrive** [InwoongLee/TS-LSTM#10]
Hello
        I have one question about Actions_01-49.txt and Actions_50-60.txt.I want to know how to ensure the content of Actions_01-49.txt and Actions_50-60.txt? Such as, 

in

and 

in 
![Uploading image.png…]()

**Comment by JiajiaStrive** [comment]
Such as
1,65,1
66,71,2
in
S004C003P003R001A035.skeleton
1,65,1
66,71,2
and
primary
1,74,2
secondary
1,74,1
in
S001C001P001R001A050.skeleton
primary
1,74,2
secondary
1,74,1
Look forward to your reply!

**Comment by m1kyd** [comment]
The numbers mean the index of frames  we chose in a skeleton sequence.
From Action 1 to 49, for example, 1, 65, 1 means that we chose 1st skeleton from 1st to 65th frame and 66, 71, 2 means that we chose 2nd skeleton from 66th to 71 frame.
From Action 50 to 60, we specified indexes of 2 skeletons, primary and secondary.
I hope this will be helpful to you!!

**Comment by JiajiaStrive** [comment]
Thank your reply!
Can you tell me the standard of chose which skeleton is 1st and which skeleton is 2st in action 1to 49?
Can you tell me the standard of chose which skeleton is primary and which skeleton is secondary in action 50 to 60?

**Comment by m1kyd** [comment]
Please check [this](https://github.com/InwoongLee/TS-LSTM#dataset).
We explained the standard to remove useless skeletons.

**Comment by JiajiaStrive** [comment]
thank you very much!
