### ISSUE TITLE
MSR Action3D dataset

### ISSUE THREAD

**Issue by kelvin992525** [InwoongLee/TS-LSTM#13]
I want to know how can I run this program with MSR action 3D data set, since the program seems like all for UCLA, NTU and UWA

**Comment by InwoongLee** [comment]
I'm very sorry to reply this too late. Unfortunately, I don't have the original code for MSR action 3D dataset, so I think you should refer to the TS-LSTM parameters of our iccv paper. Please refer to the paper explanation.
