### ISSUE TITLE
Regarding NTU RGB-D + 120 dataset

### ISSUE THREAD

**Issue by Anirudh257** [InwoongLee/TS-LSTM#14]
Thanks for sharing your code. I wanted to know if this same code can be used for the newer version of the dataset which has 120 classes. Can I use the same 2 Matlab files for extracting the skeleton data into CSV format? If no, what changes are required to be made in the code?

**Comment by InwoongLee** [comment]
I think you should check the dataset NTU RGB+D 120. Our code is for the NTU RGB+D 60 dataset. It's difficult to say what changes needed in the code because I didn't check the new dataset yet.

**Comment by Anirudh257** [comment]
Sure, thanks for the reply.
