### ISSUE TITLE
Question about runtime

### ISSUE THREAD

**Issue by qiuqicao77** [InwoongLee/TS-LSTM#15]
There is not runtime info in the paper. Do you remember the fps for the action recognition model?

**Comment by InwoongLee** [comment]
I'm very sorry to reply this too late. Unfortunately, I didn't check the fps at that time. You can check the inference time like the following code.
```
import torch
import time
torch.cuda.synchronize()
t = time.time()

Inference_Function()

FPS_Action = 1/(time.time() - t)
torch.cuda.synchronize()
```
